### ISSUE TITLE
another bugsack error 

### ISSUE THREAD

**Issue by Rubyurek** [xod-wow/LiteBag#33] opened 2023-02-18 13:04 UTC
2x [ADDON_ACTION_FORBIDDEN] AddOn 'LiteBag' hat versucht die geschützte Funktion 'UseAction()' aufzurufen.
[string "@!BugGrabber/BugGrabber.lua"]:480: in function <!BugGrabber/BugGrabber.lua:480>
[string "=[C]"]: in function `UseAction'
[string "@FrameXML/SecureTemplates.lua"]:364: in function `handler'
[string "@FrameXML/SecureTemplates.lua"]:690: in function <FrameXML/SecureTemplates.lua:672>
[string "@FrameXML/SecureTemplates.lua"]:704: in function <FrameXML/SecureTemplates.lua:697>
[string "@FrameXML/SecureTemplates.lua"]:746: in function `SecureActionButton_OnClick'
[string "@FrameXML/ActionButton.lua"]:89: in function `TryUseActionButton'
[string "@FrameXML/MultiActionBars.lua"]:23: in function `MultiActionButtonDown'
[string "MULTIACTIONBAR2BUTTON1"]:2: in function <[string "MULTIACTIONBAR2BUTTON1"]:1>

**Comment by mbattersby** [comment] 2023-02-19 23:56
Duplicate of #34

**Closed by mbattersby** 2023-02-19 23:56 UTC
