### ISSUE TITLE
Spellbook and Litebag error

### ISSUE THREAD

**Issue by Rubyurek** [xod-wow/LiteBag#32] opened 2023-02-17 23:27 UTC
1x [ADDON_ACTION_BLOCKED] AddOn 'LiteBag' hat versucht die geschützte Funktion 'SpellButton1:Enable()' aufzurufen.
[string "@!BugGrabber/BugGrabber.lua"]:480: in function <!BugGrabber/BugGrabber.lua:480>
[string "=[C]"]: in function `Enable'
[string "@FrameXML/SpellBookFrame.lua"]:894: in function `UpdateButton'
[string "@FrameXML/SpellBookFrame.lua"]:581: in function <FrameXML/SpellBookFrame.lua:532>

**Comment by mbattersby** [comment] 2023-02-19 23:54
This is taint, and the error message there has nothing to do with what's actually wrong (and it may not even be LiteBag).

There is no fix at this point. LiteBag doesn't touch any of the things mentioned in the error message.

I've made a consolidated taint issue to put all this in. Duplicate of #34.

**Closed by mbattersby** 2023-02-19 23:54 UTC
